### ISSUE TITLE
‘uint32_t’ was not declared in this scope

### ISSUE THREAD

**Issue by blshkv** [simsong/be20_api#93]
The following bug was reported using the latest git commit:
https://github.com/pentoo/pentoo-overlay/issues/1519
```
In file included from be20_api/atomic_unicode_histogram.cpp:10:
be20_api/unicode_escape.h:29:26: error: ‘uint32_t’ was not declared in this scope; did you mean ‘utf8::uint32_t’?
   29 | bool valid_utf8codepoint(uint32_t unichar); // not all unichars are valid codepoints
      |                          ^~~~~~~~
      |                          utf8::uint32_t
In file included from be20_api/utf8/checked.h:31,
                 from be20_api/utf8.h:30,
                 from be20_api/unicode_escape.h:18:
be20_api/utf8/core.h:57:29: note: ‘utf8::uint32_t’ declared here
```
Please advise

**Comment by simsong** [comment]
Hi. This works on most platforms. What platform are you compiling on? 
We probably need to add an `#include` file here. 
I need to know your OS and version number. Can you please attach to this your entire `config.log` and the full output of your `make`? Thanks.

**Comment by blshkv** [comment]
The OS is Pentoo, obviously. Please check the attached [build.log](https://github.com/pentoo/pentoo-overlay/files/11649040/build.log)
[emerge-info.txt](https://github.com/pentoo/pentoo-overlay/files/11649044/emerge-info.txt)
files our bug report.

**Comment by simsong** [comment]
Thank you for the attached files. I did not see them or the OS in your big report. Please excuse me. Can you please provide the URL? It does not seem to be here in #93

In any event, I invite you to add the appropriate `#include` for your system and then send a PR. I am not familiar with your version of Linux.

Thanks!

**Comment by blshkv** [comment]
Yeah, it is all there https://github.com/simsong/be20_api/issues/93, just check it again.
The URL itself says "pentoo" lol.

Also invited the original bug reporter https://github.com/Ultimator14 to follow up with you, as I'm unable to reproduce the bug.

Thanks for the tool btw!

**Comment by simsong** [comment]
Ah. That was not clear to me using the cell phone GitHub client. Thanks.

**Comment by simsong** [comment]
Hi. I've now spent about 2 hours trying to get a pentoo VM that I can use. I'm giving up. I finally got it installed on a VM at vultr but I can't get the IP networking to come up. If you can set up a VM for me to use, I'll try it out. 

Should I try gentoo? Is this a problem on that OS, or just on pentoo?

**Comment by blshkv** [comment]
Yes, all services are OFF by default, as they should.
Try:  ```/etc/init.d/NetworkManager start```

You can install Gentoo too (good luck!), and add pentoo overlay:
```eselect repository add pentoo```

**Comment by simsong** [comment]
I brought up a VM running gentoo and ran the following installation commands:
```
emerge --ask --changed-use --oneshot net-misc/openssh
emerge --ask --verbose --update --deep --newuse @world
rc-update add sshd default
rc-service sshd start
```
I then logged in as my user an did:
```
git clone --recursive ssh://git@github.com/simsong/bulk_extractor.git
cd bulk_extractor/
sh bootstrap.sh
./configure
make
```

bulk_extractor installed without problem. However, libewf was not installed. I'll try to do that now. However, at the moment, this doesn't appear to be a problem. If you send me your ssh key, I'll let you log into the VM.

**Comment by simsong** [comment]
Okay, I just tried it with libewf. This is not happening with pentoo 6.2.8, based on Gentoo 2.13.

**Comment by blshkv** [comment]
you are doing it wrong. We create ebuilds which does everything for you. The correct way is to run:
```
emerge app-forensics/bulk_extractor
```
But anyway, as you can see, I switched to the latest tar.gz release and "fixed" the problem.
I asked the reporter to follow up with you in this bug report but he seems not interested.
So let it rest in peace. I'll come back if the next release would be affected (and it might).

**Comment by simsong** [comment]
I guess I should learn the emerge thing. Thanks.


----
Sent from my phone.

On Jun 18, 2023, at 9:40 PM, Anton Bolshakov ***@***.***> wrote:

﻿

you are doing it wrong. We create ebuilds which does everything for you. The correct way is to run:

emerge app-forensics/bulk_extractor


But anyway, as you can see, I switched to the latest tar.gz release and "fixed" the problem.
I asked the reporter to follow up with you in this bug report but he seems not interested.
So let it rest in peace. I'll come back if the next release would be affected (and it might).

**Comment by Ultimator14** [comment]
Sorry for my absence. I was on holiday last week.  
I tested the latest release as you described (via git clone). The build fails with the same error as the pentoo package before.
However I also tested it on a recent ubuntu and there it works fine.

I'm on testing in gentoo so I probably have newer software than you did. I'll try to downgrade some packages to see where the problem is and report back here if I find out. Since both of you can't reproduce it, this could just as well be a problem of my setup.

Thanks for your commitment.

**Comment by simsong** [comment]
If there is a gentoo build action on GitHub Actions, I’m happy to add it to the validation tests.


----
Sent from my phone.

On Jun 19, 2023, at 9:21 AM, Ultimator14 ***@***.***> wrote:

﻿

Sorry for my absence. I was on holiday last week.
I tested the latest release as you described (via git clone). The build fails with the same error as the pentoo package before.
However I also tested it on a recent ubuntu and there it works fine.

I'm on testing in gentoo so I probably have newer software than you did. I'll try to downgrade some packages to see where the problem is and report back here if I find out. Since both of you can't reproduce it, this could just as well be a problem of my setup.

Thanks for your commitment.

**Comment by Ultimator14** [comment]
The build is successful with gcc version < 13.  
I suppose the problem is that the `cstdint` header is used less widely in libstdc++ as described in the gcc 13 porting tips [here](https://gcc.gnu.org/gcc-13/porting_to.html).  
The fix would be the same as already applied in the pentoo repository. The previously implicitly imported lib should be imported explicitly. 
```diff
diff --git a/unicode_escape.h b/unicode_escape.h
index a715d1d..467ee4b 100644
--- a/unicode_escape.h
+++ b/unicode_escape.h
@@ -7,6 +7,7 @@
 #ifndef UNICODE_ESCAPE_H
 #define UNICODE_ESCAPE_H
 
+#include <cstdint>
 #include <cstring>
 #include <cwctype>
 #include <iostream>

```

**Comment by simsong** [comment]
Oh, that's easy. Do you want to submit a pull request?
